### ISSUE TITLE
Fix errors in help2

### ISSUE THREAD

**Issue by PhuongPhg** [PhuongPhg/SAVABLE#17]
![image](https://user-images.githubusercontent.com/59214503/79707204-dc197900-82e5-11ea-8dab-09bddfd2ba51.png)
Pleases fix this at the webhost

**Comment by PhuongPhg** [comment]
@s0ys4uc3 write your problems here :vv

**Comment by migloh** [comment]
Cannot update password to the database!

**Comment by PhuongPhg** [comment]
I think it's SQL code has some problems.
The origin code in git is
```
mysqli_query($connect, "UPDATE UserAccount SET password='$newpass' WHERE email=$_SESSION['email']");
```
But in the webhost manager, you used
```
mysqli_query($connect, "UPDATE 'UserAccount' SET 'password'=$newpass WHERE 'email'=$useremail");
```
Let's check it again

**Comment by PhuongPhg** [comment]
Any btw, i think it's better to let these code  include outside the if method
```
if ($_SERVER["REQUEST_METHOD"] == "POST"){
	include "connection.php";
	$newpass = "";
	$reenpass = "";
```
Like this
```
include "connection.php";
$newpass = "";
$reenpass = "";
if ($_SERVER["REQUEST_METHOD"] == "POST"){
```
