### ISSUE TITLE
Clean the code tab!

### ISSUE THREAD

**Issue by migloh** [PhuongPhg/SAVABLE#22]
Put all source code into folders, just leave some important files like readme outside.

**Comment by PhuongPhg** [comment]
Just my opinion, the title should be "Rearrange files and folders", not clean.

Please give more details about how we gonna rearrange it? Like put all the css files in a folder? or for each task will be in one folder?

**Comment by migloh** [comment]
I still have no idea.
Do you think that put all source files in ONE folder is ok?

**Comment by PhuongPhg** [comment]
I think it should be 1 css folder, 1 php in 1 folder? I guess?
So can you do this? @s0ys4uc3

**Comment by dinhanhx** [comment]
## Repos structure
In my opinion, I think you guys should divide your repos in to folders. For example:
```
SAVABLE
+--- graphics
|     +--- a.png
|
+--- html_files
|     +--- template.html
|
+--- css_files
|     +--- style.css
|
+--- js_files
|     +--- func.js
|
+--- php_files
|     +--- home.php 
|
+--- cypress
|     +--- test_code.js
|
+--- README.md
+--- the-starting-page-of-all.html
```
Also each folder you can add a README.md to make the folder for meaningful.

**Comment by dinhanhx** [comment]
By the way, the label `enhancement` is not suitable for this issue. it should be like `request`
