### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by PhuongPhg** [PhuongPhg/SAVABLE#23]
README.md file is kind of....old

Update the file, can have include like ("How to test it, how to use")
Or what was done, what will be the next version/updates.
Update the demo link, too

**Comment by dinhanhx** [comment]
## README.md (of the repos)
Normally, most of GitHub repos, people don't use README.md as a project proposal. README.md is like the description of your repos, what repos is, how to use repos, information about the developers.

[Example 1](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)

[Example 2](https://github.com/jehna/readme-best-practices)

[Example 3](https://github.com/matiassingers/awesome-readme/blob/master/readme.md)

**Comment by dinhanhx** [comment]
@PhuongPhg All .md files look good to me, I think it's time to close this issue
