### ISSUE TITLE
Reorganize .php .hmtl .css .js files/ Reorganize your repos

### ISSUE THREAD

**Issue by dinhanhx** [PhuongPhg/SAVABLE#24]
## Repos structure
In my opinion, I think you guys should divide your repos in to folders. For example:
```
SAVABLE
+--- graphics
|     +--- a.png
|
+--- html_files
|     +--- template.html
|
+--- css_files
|     +--- style.css
|
+--- js_files
|     +--- func.js
|
+--- php_files
|     +--- home.php 
|
+--- cypress
|     +--- test_code.js
|
+--- README.md
+--- the-starting-page-of-all.html
```
Also each folder you can add a README.md to make the folder for meaningful. 
## README.md (of the repos)
Normally, most of GitHub repos, people don't use README.md as a project proposal. README.md is like the description of your repos, what repos is, how to use repos, information about the developers.

[Example 1](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)

[Example 2](https://github.com/jehna/readme-best-practices)

[Example 3](https://github.com/matiassingers/awesome-readme/blob/master/readme.md)

**Comment by dinhanhx** [comment]
Related issue #22 #23

**Comment by dinhanhx** [comment]
@s0ys4uc3 @PhuongPhg  this should be also label `support` or `suggestion` or `repos-structure`

**Comment by PhuongPhg** [comment]
Ohhhh
Thanks a lot for your advise, god-of-meme @dinhanhx 😉 I think we are much clear now. It’s so detailed 😄

We will see and change these things soon 🤗

**Comment by dinhanhx** [comment]
@PhuongPhg  I also want to say that. You should divide your Project section into smaller projects.

Divide `SAVABLE` project into like `Implementation of frontend` project, `Implementation of backend` project and `cypress` project.

**Comment by PhuongPhg** [comment]
Yesss

I’m still thinking and considering to separate the project sections by its tasks, but frontend and backend are much easier to understand now 😯

**Comment by dinhanhx** [comment]
Keep doing great, your web app has potential!!!

**Comment by Huy-Ngo** [comment]
IMHO, `html/`, `css/`, `js/` (or `javascript/`) would suffice, since it's quite obvious they're files

**Comment by dinhanhx** [comment]
Yea, my example is not good enough.

**Comment by migloh** [comment]
Thanks a lots for your advices you guys!

**Comment by dinhanhx** [comment]
Don't thank me, must thank Huy.
