### ISSUE TITLE
Testcase for sign up page

### ISSUE THREAD

**Issue by PhuongPhg** [PhuongPhg/SAVABLE#35]
The test must check the result when 
- [x] Missing username/password/email, etc.
- [x] Email taken
- [x] Username taken
- [x] Unsupported char in username
- [x] Invalid year of birth

**Comment by dinhanhx** [comment]
@s0ys4uc3 I think you should add
- [ ] Unsupported char in username

`!@#$%^&*` maybe?

**Comment by PhuongPhg** [comment]
Oh thanks, I forgot about that. I will add pattern `[A-Za-z0-9_]{6, }` to the file 👍
