### ISSUE TITLE
[Bug] Unavailable link in about.html

### ISSUE THREAD

**Issue by dinhanhx** [PhuongPhg/SAVABLE#36]
Hey @s0ys4uc3 and @PhuongPhg 
This link in side this element is not found.
https://github.com/PhuongPhg/SAVABLE/blob/cf0f5c9d66d04b36e8c13302238feab5f58e367d/html/about.html#L39
I think it should be this [one](https://github.com/PhuongPhg/SAVABLE/blob/master/documentation/SAVABLE_proposal.md)

**Comment by PhuongPhg** [comment]
Yes, we forgot to change the links. Thanks for checking that
